-- AlterTable
ALTER TABLE "engine_config" ADD COLUMN     "adaptive_sequencing_enabled" BOOLEAN,
ADD COLUMN     "adaptive_sequencing_latency_threshold_ms" INTEGER,
ADD COLUMN     "audit_log_retention_days" INTEGER,
ADD COLUMN     "auto_unwind_delay_ms" INTEGER,
ADD COLUMN     "auto_unwind_enabled" BOOLEAN,
ADD COLUMN     "auto_unwind_max_loss_pct" DOUBLE PRECISION,
ADD COLUMN     "calibration_cron_expression" TEXT,
ADD COLUMN     "calibration_enabled" BOOLEAN,
ADD COLUMN     "cluster_llm_timeout_ms" INTEGER,
ADD COLUMN     "csv_enabled" BOOLEAN,
ADD COLUMN     "detection_gas_estimate_usd" DECIMAL(20,8),
ADD COLUMN     "detection_min_edge_threshold" DECIMAL(20,8),
ADD COLUMN     "detection_position_size_usd" DECIMAL(20,8),
ADD COLUMN     "discovery_cron_expression" TEXT,
ADD COLUMN     "discovery_enabled" BOOLEAN,
ADD COLUMN     "discovery_llm_concurrency" INTEGER,
ADD COLUMN     "discovery_max_candidates_per_contract" INTEGER,
ADD COLUMN     "discovery_prefilter_threshold" DECIMAL(20,8),
ADD COLUMN     "discovery_run_on_startup" BOOLEAN,
ADD COLUMN     "discovery_settlement_window_days" INTEGER,
ADD COLUMN     "execution_min_fill_ratio" DECIMAL(20,8),
ADD COLUMN     "exit_confidence_drop_pct" INTEGER,
ADD COLUMN     "exit_edge_evap_multiplier" DOUBLE PRECISION,
ADD COLUMN     "exit_min_depth" INTEGER,
ADD COLUMN     "exit_mode" TEXT,
ADD COLUMN     "exit_profit_capture_ratio" DOUBLE PRECISION,
ADD COLUMN     "exit_risk_budget_pct" INTEGER,
ADD COLUMN     "exit_risk_rank_cutoff" INTEGER,
ADD COLUMN     "exit_time_decay_horizon_h" INTEGER,
ADD COLUMN     "exit_time_decay_steepness" DOUBLE PRECISION,
ADD COLUMN     "exit_time_decay_trigger" DOUBLE PRECISION,
ADD COLUMN     "gas_buffer_percent" INTEGER,
ADD COLUMN     "gas_pol_price_fallback_usd" DECIMAL(20,8),
ADD COLUMN     "gas_poll_interval_ms" INTEGER,
ADD COLUMN     "kalshi_polling_concurrency" INTEGER,
ADD COLUMN     "llm_auto_approve_threshold" INTEGER,
ADD COLUMN     "llm_escalation_max" INTEGER,
ADD COLUMN     "llm_escalation_min" INTEGER,
ADD COLUMN     "llm_escalation_model" TEXT,
ADD COLUMN     "llm_escalation_provider" TEXT,
ADD COLUMN     "llm_max_tokens" INTEGER,
ADD COLUMN     "llm_min_review_threshold" INTEGER,
ADD COLUMN     "llm_primary_model" TEXT,
ADD COLUMN     "llm_primary_provider" TEXT,
ADD COLUMN     "llm_timeout_ms" INTEGER,
ADD COLUMN     "min_annualized_return" DECIMAL(20,8),
ADD COLUMN     "orderbook_staleness_threshold_ms" INTEGER,
ADD COLUMN     "polling_interval_ms" INTEGER,
ADD COLUMN     "polymarket_order_poll_interval_ms" INTEGER,
ADD COLUMN     "polymarket_order_poll_timeout_ms" INTEGER,
ADD COLUMN     "polymarket_polling_concurrency" INTEGER,
ADD COLUMN     "polymarket_settlement_gas_units" INTEGER,
ADD COLUMN     "resolution_poller_batch_size" INTEGER,
ADD COLUMN     "resolution_poller_cron_expression" TEXT,
ADD COLUMN     "resolution_poller_enabled" BOOLEAN,
ADD COLUMN     "risk_aggregate_cluster_limit_pct" DECIMAL(20,8),
ADD COLUMN     "risk_cluster_hard_limit_pct" DECIMAL(20,8),
ADD COLUMN     "risk_cluster_soft_limit_pct" DECIMAL(20,8),
ADD COLUMN     "risk_daily_loss_pct" DECIMAL(20,8),
ADD COLUMN     "risk_max_open_pairs" INTEGER,
ADD COLUMN     "risk_max_position_pct" DECIMAL(20,8),
ADD COLUMN     "stress_test_default_daily_vol" DECIMAL(20,8),
ADD COLUMN     "stress_test_min_snapshots" INTEGER,
ADD COLUMN     "stress_test_scenarios" INTEGER,
ADD COLUMN     "telegram_buffer_max_size" INTEGER,
ADD COLUMN     "telegram_circuit_break_ms" INTEGER,
ADD COLUMN     "telegram_max_retries" INTEGER,
ADD COLUMN     "telegram_send_timeout_ms" INTEGER,
ADD COLUMN     "telegram_test_alert_cron" TEXT,
ADD COLUMN     "telegram_test_alert_timezone" TEXT,
ADD COLUMN     "ws_staleness_threshold_ms" INTEGER;
